# Generated by Django 4.2.7 on 2025-09-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(max_length=30, null=True),
        ),
       migrations.AlterField(
                model_name='cart',
                name='session_key',
                field=models.CharField(max_length=40, null=True),
            )
    ]
