# Generated by Django 4.2.7 on 2025-09-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_remove_order_cart_order_cart_items_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('online_payment', 'Online Payment')], default='cash_on_delivery', max_length=20),
        ),
    ]
