# Generated by Django 4.2.7 on 2025-09-04 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productvariant_sku'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
    ]
